import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fa",
        "on-surface": "#111c2c",
        "on-surface-variant": "#554434",
        "inverse-surface": "#263142",
        "inverse-on-surface": "#ebf1ff",
        outline: "#887361",
        "outline-variant": "#dbc2ad",
        "surface-tint": "#8b5000",
        primary: "#8b5000",
        "on-primary": "#ffffff",
        "primary-container": "#ff9800",
        "on-primary-container": "#653900",
        "inverse-primary": "#ffb870",
        secondary: "#4e5e82",
        "on-secondary": "#ffffff",
        "secondary-container": "#c4d4fe",
        "on-secondary-container": "#4b5b7f",
        tertiary: "#625f4d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b6b19c",
        "on-tertiary-container": "#474434",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdcbe",
        "primary-fixed-dim": "#ffb870",
        "on-primary-fixed": "#2c1600",
        "on-primary-fixed-variant": "#693c00",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b6c6f0",
        "on-secondary-fixed": "#071b3b",
        "on-secondary-fixed-variant": "#364669",
        "tertiary-fixed": "#e9e2cc",
        "tertiary-fixed-dim": "#ccc6b1",
        "on-tertiary-fixed": "#1e1c0e",
        "on-tertiary-fixed-variant": "#4a4737",
        background: "#f9f9ff",
        "on-background": "#111c2c",
        "surface-variant": "#d8e3fa",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "container-margin": "16px",
        gutter: "12px",
      },
      fontFamily: {
        h1: ["Montserrat", "sans-serif"],
        "h1-mobile": ["Montserrat", "sans-serif"],
        h2: ["Montserrat", "sans-serif"],
        h3: ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "price-display": ["Montserrat", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        h1: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "30px", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "price-display": ["22px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;