import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1d1d03",
        "primary-container": "#ff8c00",
        "background": "#fff8f5",
        "tertiary-fixed": "#ffdbd0",
        "on-background": "#1e1b18",
        "error": "#ba1a1a",
        "surface-bright": "#fff8f5",
        "on-surface": "#1e1b18",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#77574d",
        "surface-container-low": "#fbf2ed",
        "secondary-fixed": "#e6e5b9",
        "on-tertiary-fixed": "#2c160e",
        "secondary": "#60603e",
        "surface-tint": "#904d00",
        "surface": "#fff8f5",
        "on-primary": "#ffffff",
        "on-surface-variant": "#564334",
        "error-container": "#ffdad6",
        "primary": "#904d00",
        "tertiary-container": "#c8a195",
        "tertiary-fixed-dim": "#e7bdb1",
        "surface-container-highest": "#e9e1dc",
        "on-tertiary-fixed-variant": "#5d4037",
        "on-primary-fixed": "#2f1500",
        "primary-fixed": "#ffdcc3",
        "outline-variant": "#ddc1ae",
        "outline": "#897362",
        "inverse-primary": "#ffb77d",
        "inverse-surface": "#34302c",
        "surface-container": "#f5ece7",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#484828",
        "inverse-on-surface": "#f8efea",
        "secondary-fixed-dim": "#cac99f",
        "on-primary-fixed-variant": "#6e3900",
        "primary-fixed-dim": "#ffb77d",
        "on-primary-container": "#623200",
        "on-secondary-container": "#666643",
        "surface-variant": "#e9e1dc",
        "secondary-container": "#e6e5b9",
        "on-tertiary-container": "#53382f",
        "surface-dim": "#e1d8d4",
        "surface-container-high": "#efe6e2",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        sm: "12px",
        gutter: "24px",
        "container-max": "1200px",
        lg: "48px",
        xl: "80px",
        xs: "4px",
        base: "8px",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
